#!/bin/sh
#
#       <FAIL-SCRIPT>
#
#       Called in the event that preinstall (bootstrap) fails
#
#       Copyright 2008 Dell Inc.
#           Mario Limonciello <Mario_Limonciello@Dell.com>
#           Hatim Amro <Hatim_Amro@Dell.com>
#           Michael E Brown <Michael_E_Brown@Dell.com>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

echo "FATAL ERROR IN INSTALLATION... ABORTING." > /dev/tty1

# this script not meant to be replaced by FI team

#tell the user to reboot
try_splash_quit \
    "FAILURE during bootstrap process.
    \nA debug shell has been spawned to debug with on /dev/tty12.
    \nYou can switch to it by pressing ctrl-alt-f12."

if ! grep -q DEBUG /proc/cmdline; then
    while true; do
        /bin/sh 2>/dev/tty12 1>/dev/tty12 </dev/tty12
    done
fi


