#!/bin/sh
#
#       <FAIL-SCRIPT>
#
#       Script called in the event that a postinstall (chroot) script fails
#
#       Copyright 2008 Dell Inc.
#           Mario Limonciello <Mario_Limonciello@Dell.com>
#           Hatim Amro <Hatim_Amro@Dell.com>
#           Michael E Brown <Michael_E_Brown@Dell.com>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

# BE AWARE THAT THIS SCRIPT IS CALLED FROM OUTSIDE THE CHROOT.
# The OS is mounted under /target

. /cdrom/scripts/chroot-scripts/fifuncs "target"

set -x
set -e

IFHALT "(FAIL) Clean-Up & Report FI logs ..."

rm -rf /etc/mtab
ln -s /proc/mounts /etc/mtab
mount -o remount,rw /cdrom

IFHALT "Reporting logs to DMP"
cp -f /target/var/log/installer/chroot.sh.log /tmp/fist.err
[ -f /dell/fist/tal ] && /dell/fist/tal PutFiles /tmp/fist.err
sync
dpkg -r fist

IFHALT "(FAIL) Report to FI logs.. Done!"
