#!/bin/sh
#
#       <fifuncs>
#
#       Common functions that can be used for postinstall (chroot) scripts
#
#       Copyright 2008 Dell Inc.
#           Mario Limonciello <Mario_Limonciello@Dell.com>
#           Hatim Amro <Hatim_Amro@Dell.com>
#           Michael E Brown <Michael_E_Brown@Dell.com>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

wd=""$1""

screenmsg() {
    echo $* > /dev/tty1 2>&1
}

IFHALT() {
    if [ -f /$wd/tmp/superhalt.flg ]; then
        touch /tmp/halt.flg
        screenmsg "Halting ---> "$1
        set +x
        while [ -f /tmp/halt.flg ]; do
            sleep 2
        done
        set -x
    else
        screenmsg "Message --->: $1"
    fi
}

match_system_device()
{
    if [ "$1" = "usb" ]; then
        VENDOR_FILE="idVendor"
        DEVICE_FILE="idProduct"
    elif [ "$1" = "pci" ]; then
        VENDOR_FILE="vendor"
        DEVICE_FILE="device"
    else
        echo "$1 bus is not supported"
        return 1
    fi
    if [ -z "$2" ] || [ -z "$3" ]; then
        echo "Need Vendor and Product arguments"
        return 1
    fi
    DEVICES=$(find -L /sys/bus/$1/devices -maxdepth 2 -name $DEVICE_FILE)
    for file in $DEVICES; do
        CHECK_DEVICE=$(cat $file)
        DIRECTORY=$(dirname $file)
        CHECK_VENDOR=$(cat $DIRECTORY/$VENDOR_FILE)
        if [ "$CHECK_VENDOR" != "$2" ] && [ "$CHECK_VENDOR" != "0x$2" ]; then
            continue
        fi
        if [ "$CHECK_DEVICE" = "$3" ] || [ "$CHECK_DEVICE" = "0x$3" ]; then
            return 0
        fi
    done
    return 1
}

