#!/bin/bash
#
#       <fifuncs>
#
#       Common functions that can be used for postinstall (chroot) scripts
#
#       Copyright 2008 Dell Inc.
#           Mario Limonciello <Mario_Limonciello@Dell.com>
#           Hatim Amro <Hatim_Amro@Dell.com>
#           Michael E Brown <Michael_E_Brown@Dell.com>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

wd=""$1""

screenmsg() {
    echo $* > /dev/tty1 2>&1
}

IFHALT() {
    if [ -f /$wd/tmp/superhalt.flg ]; then
        touch /tmp/halt.flg
        screenmsg "Halting ---> "$1
        set +x
        while [ -f /tmp/halt.flg ]; do
            sleep 2
        done
        set -x
    else
        screenmsg "Message --->: $1"
    fi
}

