#!/bin/bash
#
#       <run_chroot>
#
#       Individually launches each postinstall (chroot) script
#       Both Python (.py) and Shell (.sh) scripts are supported
#       Scripts are launched in this order:
#        > os-pre
#        > fish
#        > os-post
#
#       Copyright 2008 Dell Inc.
#           Mario Limonciello <Mario_Limonciello@Dell.com>
#           Hatim Amro <Hatim_Amro@Dell.com>
#           Michael E Brown <Michael_E_Brown@Dell.com>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

. /mnt/scripts/chroot-scripts/fifuncs ""

set -x
set -e

trap 'echo Command FAILED: $i' ERR

echo "in $0"

sync
[ -f /mnt/superhalt.flg ] && touch /tmp/superhalt.flg
sync

IFHALT "Chroot-scripts execution start..."
for d in /mnt/scripts/chroot-scripts/os-pre /mnt/scripts/chroot-scripts/fish /mnt/scripts/chroot-scripts/os-post
do
    IFHALT "Executing Scripts in DIR: $d"
    for i in $d/*.sh $d/*.py;
    do
        echo "running chroot script: $i"  > /dev/tty12
        IFHALT $i
        ext=`echo $i | sed 's/^.*\.//'`
        if [ $ext == "sh" ]; then
            [ -e $i ] && . $i
        elif [  $ext == "py" ]; then
            [ -e $i ] && python $i
        fi
    done
done
sync;sync
IFHALT "Done with chroot scripts"
