#!/bin/sh
#
#       <SUCCESS-SCRIPT>
#
#       Called in the event that postinstall (chroot) steps complete successfully
#
#       Copyright 2008 Dell Inc.
#           Mario Limonciello <Mario_Limonciello@Dell.com>
#           Hatim Amro <Hatim_Amro@Dell.com>
#           Michael E Brown <Michael_E_Brown@Dell.com>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

# BE AWARE THAT THIS SCRIPT IS CALLED FROM OUTSIDE THE CHROOT.
# The OS is mounted under $TARGET

. /cdrom/scripts/chroot-scripts/fifuncs "target"

set -x
set -e

IFHALT "(SUCCESS) Clean-Up and Report FI logs ..." > /dev/tty12

rm -rf /etc/mtab
ln -s /proc/mounts /etc/mtab
mount -o remount,rw /cdrom

IFHALT "Clean up FI Env..."
rm -rf /cdrom/scripts/chroot-scripts/os-post/95-set_UTC_TZ.sh
rm -rf /cdrom/misc/run-tz-fix
rm -rf /cdrom/misc/tz_offset.py
rm -rf /cdrom/command.com
rm -rf /cdrom/autoexec.bat
rm -rf /cdrom/dellbio.bin
rm -rf /cdrom/dellrmk.bin
rm -rf /cdrom/linld.com
rm -rf /cdrom/cmd.cfg

IFHALT "Clean up FID FAIL & SUCCESS scripts..."
rm -rf /cdrom/scripts/chroot-scripts/FAIL-SCRIPT
echo -e "#!/bin/sh\n# Fail code goes here..." > /cdrom/scripts/chroot-scripts/FAIL-SCRIPT
rm -rf /cdrom/scripts/chroot-scripts/SUCCESS-SCRIPT
echo -e "#!/bin/sh\n# Success code goes here..." > /cdrom/scripts/chroot-scripts/SUCCESS-SCRIPT

IFHALT "Remove Bad line in /etc/fstab"
sed -i '/\/dev\/sda2/d' /target/etc/fstab

IFHALT "Report the LOG... If applicable"
chroot $TARGET chattr -a $LOG/chroot.sh.log
mv -f $TARGET/$LOG/chroot.sh.log /tmp/fist.log
if [ -f /dell/fist/tal ]; then
	/dell/fist/tal PutFiles /tmp/fist.log
	dpkg -r fist
	rm -rf /dell
	rm -rf /cdrom/debs/fist
fi

IFHALT "SUCCESS-SCRIPT is Done!"
