#!/bin/sh
#
#       <SUCCESS-SCRIPT>
#
#       Called in the event that postinstall (chroot) steps complete successfully
#
#       Copyright 2008 Dell Inc.
#           Mario Limonciello <Mario_Limonciello@Dell.com>
#           Hatim Amro <Hatim_Amro@Dell.com>
#           Michael E Brown <Michael_E_Brown@Dell.com>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

# BE AWARE THAT THIS SCRIPT IS CALLED FROM OUTSIDE THE CHROOT.
# The OS is mounted under $TARGET

. /cdrom/scripts/chroot-scripts/fifuncs "target"

set -x
set -e

if [ "$BOOTDEV" = "$TARGETDEV" ]; then
    mount -o remount,rw /cdrom

    IFHALT "Clean up FID FAIL & SUCCESS scripts..."
    rm -rf /cdrom/scripts/chroot-scripts/FAIL-SCRIPT
    cat > /cdrom/scripts/chroot-scripts/FAIL-SCRIPT << EOF
. /cdrom/scripts/chroot-scripts/fifuncs "target"
set -x

IFHALT "(FAIL) Clean-Up & Report FI logs ..."

if [ "\$BOOTDEV" = "\$TARGETDEV" ]; then
    mount -o remount,rw /cdrom

    IFHALT "Resetting grub fail state"
    [ -s /cdrom/grub/grubenv ] || rm -f /cdrom/grub/grubenv
    mkdir -p /cdrom/grub
    grub-editenv /cdrom/grub/grubenv set recordfail=1
fi
EOF

    rm -rf /cdrom/scripts/chroot-scripts/SUCCESS-SCRIPT
    cat > /cdrom/scripts/chroot-scripts/SUCCESS-SCRIPT << EOF
. /cdrom/scripts/chroot-scripts/fifuncs "target"
set -x

IFHALT "(SUCCESS) Clean-Up and Report FI logs ..."

chroot $TARGET chattr -a $LOG/chroot.sh.log

if [ "\$BOOTDEV" = "\$TARGETDEV" ]; then
    mount -o remount,rw /cdrom

    IFHALT "Resetting grub fail state"
    [ -s /cdrom/grub/grubenv ] || rm -f /cdrom/grub/grubenv
    mkdir -p /cdrom/grub
    grub-editenv /cdrom/grub/grubenv unset recordfail
fi

#This will be rebuilt before OEM config
rm -f /etc/apt/sources.list.d/dell.list
EOF

    #We don't need to set this executable because on FAT32
    #everything is already executable
    /cdrom/scripts/chroot-scripts/SUCCESS-SCRIPT

    IFHALT "Clean up FI Env..."
    rm -rf /cdrom/scripts/chroot-scripts/os-post/95-set_UTC_TZ.sh
    rm -rf /cdrom/misc/run-tz-fix
    rm -rf /cdrom/misc/tz_offset.py
    rm -rf /cdrom/command.com
    rm -rf /cdrom/autoexec.bat
    rm -rf /cdrom/dellbio.bin
    rm -rf /cdrom/dellrmk.bin
    rm -rf /cdrom/linld.com
    rm -rf /cdrom/cmd.cfg

    IFHALT "Report the LOG... If applicable"
    if [ -f /dell/fist/tal ]; then
        cp $TARGET/$LOG/chroot.sh.log /tmp/fist.log
        /dell/fist/tal PutFiles /tmp/fist.log
        rm -rf /cdrom/debs/fist
    fi
fi

IFHALT "(SUCCESS) Report to logs.. Done!"
